/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ktae23;

import java.time.LocalDate;
import java.time.YearMonth;
import java.util.List;

public class KoreaHolidayClient {

    private final String apiKey;

    public KoreaHolidayClient(final String apiKey) {
        this.apiKey = apiKey;
    }

    public boolean isHoliday(final LocalDate date) {
        final YearMonth yearMonth = YearMonth.from(date);
        final List<LocalDate> holidaysInMonth = getHolidaysInMonth(yearMonth);
        return holidaysInMonth.contains(date);
    }

    public boolean isWeekend(final LocalDate date) {
        return date.getDayOfWeek().getValue() >= 6;
    }

    public LocalDate afterNWorkingDays(final LocalDate startDate, final int n) {
        LocalDate currentDate = startDate;
        int daysAdded = 0;

        while (daysAdded < n) {
            currentDate = currentDate.plusDays(1);
            if (!isHoliday(currentDate) && !isWeekend(currentDate)) {
                daysAdded++;
            }
        }
        return currentDate;
    }

    public LocalDate beforeNWorkingDays(final LocalDate startDate, final int n) {
        LocalDate currentDate = startDate;
        int daysSubtracted = 0;

        while (daysSubtracted < n) {
            currentDate = currentDate.minusDays(1);
            if (!isHoliday(currentDate) && !isWeekend(currentDate)) {
                daysSubtracted++;
            }
        }
        return currentDate;
    }

    public List<LocalDate> getHolidaysInMonth(final YearMonth yearMonth) {
        return List.of(); // Placeholder for actual API response
    }

    public List<LocalDate> getHolidaysInYear(final int year) {
        return List.of(); // Placeholder for actual API response
    }
}
